// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK9YnywS1GC_b2wc49OoG_NyhxdM_PUaU',
    appId: '1:792087409562:web:f4e723ad9b86e01789c023',
    messagingSenderId: '792087409562',
    projectId: 'instastore-29d4f',
    authDomain: 'instastore-29d4f.firebaseapp.com',
    storageBucket: 'instastore-29d4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzd3ko48EU-AdY63qMF2z4iDJGJ-5eQAk',
    appId: '1:792087409562:android:14e6d20b8ff62e8b89c023',
    messagingSenderId: '792087409562',
    projectId: 'instastore-29d4f',
    storageBucket: 'instastore-29d4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy_yh29xtyep-1DN1AJOmyLaPIIrP_UcU',
    appId: '1:792087409562:ios:464b8b6e8e00d5a389c023',
    messagingSenderId: '792087409562',
    projectId: 'instastore-29d4f',
    storageBucket: 'instastore-29d4f.appspot.com',
    iosBundleId: 'co.prograde.store.instaStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy_yh29xtyep-1DN1AJOmyLaPIIrP_UcU',
    appId: '1:792087409562:ios:464b8b6e8e00d5a389c023',
    messagingSenderId: '792087409562',
    projectId: 'instastore-29d4f',
    storageBucket: 'instastore-29d4f.appspot.com',
    iosBundleId: 'co.prograde.store.instaStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK9YnywS1GC_b2wc49OoG_NyhxdM_PUaU',
    appId: '1:792087409562:web:20c21ead1ce1c30189c023',
    messagingSenderId: '792087409562',
    projectId: 'instastore-29d4f',
    authDomain: 'instastore-29d4f.firebaseapp.com',
    storageBucket: 'instastore-29d4f.appspot.com',
  );

}